### ISSUE TITLE
Resources are being requested (loaded) multiple times.

### ISSUE THREAD

**Issue by imjamesb** [fredrik-aschehoug/info134-folk#4]
Resource files (the resources the task says to use) are being loaded multiple (and unnecessary) times. The resources should be loaded once, in e.g. `app.js` file. If one need to share the resource data to other scripts one can use the [`window`](https://developer.mozilla.org/en-US/docs/Web/API/Window) object to store them in the window. For example:

```js
window.befolkning = new Population(getURL("104857"));
window.sysselsatte = new Employment(getURL("100145"));
window.utdanning = new Education(getURL("85432"));
```

Those properties are now accessible in all scripts (that run after the properties has been created). One also don't need to write `window.` before calling/getting the property name in the `window` object, because all scripts uses the `window` element as an environment, e.g. `window.fetch(url)` can be called using `fetch(url)`.

Where the resources are being requested:

- [js/app.js](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/app.js)
- [js/canvasGraphDisplay.js](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/canvasGraphDisplay.js)

**Comment by Erlvee** [comment]
Hello ihack 2712, this is a temporary solution while things are in testing. Resources will be called once through app.js when its finished.

Regards Erlend Vee
