### ISSUE TITLE
Incorrect use of JS Doc

### ISSUE THREAD

**Issue by imjamesb** [fredrik-aschehoug/info134-folk#5]
I've seen a lot of incorrectly used [`@callback` jsdoc tags](http://usejsdoc.org/tags-callback.html). According to [Use JSDoc](http://usejsdoc.org/) (who are also responsible for jsdoc syntax standards) the `@callback` tags are used to define how a callback should look like in code.

Here are the incorrect callback tags;

- [js/app.js:13](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/app.js#L13)
- [js/app.js:23](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/app.js#L23)
- [js/app.js:30](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/app.js#L30)
- [js/app.js:35](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/app.js#L35)
- [js/canvasGraphDisplay.js:13](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/canvasGraphDisplay.js#L13)
- [js/canvasGraphDisplay.js:23](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/canvasGraphDisplay.js#L23)
- [js/canvasGraphDisplay.js:30](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/canvasGraphDisplay.js#L30)
- [js/canvasGraphDisplay.js:35](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/canvasGraphDisplay.js#L35)

Another `@callback` tag was almost used correctly, but here it seems to just explain what a function does. If people look in the code they might understand, but if one uses the jsdoc parser it can look very weird in many themes, including the default theme will also mess up this. The mistake can be found in [js/createDetails:320](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/createDetails.js#L320).

The correct usage of a `@callback` tag would look like this:

```js
/**
 * A callback method for when a certain
 * event is fired.
 * @callback ExampleCallback
 * @param {Event} event The event object that was fired.
 * @param {string} example Another example param..
 */
```

**Note** that there is no function attached to the callback, however to link to the callback one can do:

```js
/**
 * This method is triggered when some
 * example event happens.
 * @type {ExampleCallback}
 */
SomeDOMElement.onexample = event => console.log("Hello!");
```

One can also use the "link" in function parameters:

```js
/**
 * A function that triggers an event.
 * @param {Event} event The event object to send to the callback.
 * @param {ExampleCallback} callback The callback function.
 */
function someFunc (event, callback)
{
  callback(event, "some example text");
}
```

**Another Note**: The type definition(s) / callback definition(s) only needs to be written in one file, usually it's written in the same file it's being used in. Either was, as long as there is one typedef/callback defining the type for the callback it can be used in any other file as jsdoc has now understood that "this thing" means "that thing".

Another thing I found was incorrect jsdoc syntax for the rest/spread operator. In [js/createDetails:28](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/createDetails.js#L28) there's a function:

```js
/**
 * Append html nodes to a parent node
 * @function
 * @param {HTMLElement} node - Parent node
 * @param {...HTMLElement} childs - Child nodes to append
 */
function appendNodes (node, ...childs)
{
  // ...
}
```

In the code above (taken from [source code](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/createDetails.js#L28)) there is one issue, and one unnecessary tag. In line 5 of the code above the param tries to use type `...HTMLElement` which is incorrect, it tries to access `undefined.undefined.undefined.HTMLElement`. The type should be changed to `HTMLElement[]` this defines an array of `HTMLElement`(s). The unnecessary tag `@function` (including `@method` which is an alias for `@function`) was made in the beginning of JS Doc history. The tag back then was to tell jsdoc that something is a function, although today with the more recent versions of JS Doc it basically tells JS Doc that "I wanna be a function type", the tag is now rarely seen because JS Doc will automatically understand what is and what is not a function. In very rare cases one would have to use the `@function` tag to force JS Doc to interprete the documentation and code as a function.

The correct documentation would look like:

```js
/**
 * Append HTML nodes to a parent node.
 * @param {HTMLElement} node The parent node to append the child nodes to.
 * @param {HTMLElement[]} children The child nodes to add to the parents.
 */
function appendNodes (node, ...children)
{
  // ...
}
```

Something else I also see a lot in the code is comment padding (when one writes a lot of spaces so it'll be margined to align together). This is not an issue or deprecated, but usually very rare as it's completely useless other than satisfying yourself. This is something that JS Doc automatically do for you, something else is that ` - text....` is also unnecessary, this is just removed away from the documentation, it's quicker and better for IDEs (that supports jsdoc, e.g. VSCode) to read the documentation without them (it is however not enough to change the performance, so it's probably ok to leave it as is).

Another issue would be default type names. For example in [js/createDetails.js:139](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/createDetails.js#L139) there are a lot of default types that start with capital letters, which is incorrect. Some JS doc themes will insert a link to the types it knows, and by default the default types are known and would most likely redirect to MDN. Default type names should be lowercased. E.g. `String` turns into `string`, `Number` turns into `number`, although `Array`(s) should start with a capital letter because it's not a default type. If one want to specify what the array should contain one can add square brackets after the type; e.g. `string[]` or `number[]`. Here is a [great guide for basic / default types](https://www.typescriptlang.org/docs/handbook/basic-types.html).

Last issue; [js/population.js:49](https://github.com/fredrik-aschehoug/info134-folk/blob/245dc29f56a513091862aaabb25b50ded34999df/js/population.js#L46), another incorrect use of the callback tag, guess yourselves to this one yeah? :joy: ​

**Comment by fredrik-aschehoug** [comment]
Thanks for a great explanation @ihack2712 !

**Comment by imjamesb** [comment]
Still invalid jsdoc syntax 😅

**Comment by imjamesb** [comment]
@fredrik-aschehoug 

> Still invalid jsdoc syntax 😅
